package com.pvn.dao;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import com.pvn.model.Circle;

@Component
public class CircleDaoJDBCImpl
{
	private DataSource dataSource;
	private JdbcTemplate jdbcTemplate;
	
	public DataSource getDataSource() {
		return dataSource;
	}

	@Autowired
	public void setDataSource(DataSource dataSource) {
		this.dataSource = dataSource;
		this.jdbcTemplate=new JdbcTemplate(dataSource);
	}

	public JdbcTemplate getJdbcTemplate() {
		return jdbcTemplate;
	}

	public void createCircleTable()
	{
		String sql="CREATE TABLE CIRCLE (CIRCLE_ID INT(11) NOT NULL AUTO_INCREMENT,NAME VARCHAR(45),PRIMARY KEY(CIRCLE_ID))";
		jdbcTemplate.execute(sql);
		return;
	}
	
	public int insertIntoCircle(Circle circle)
	{
		String sql="INSERT INTO CIRCLE (CIRCLE_ID,NAME) VALUES(?,?)";
		return jdbcTemplate.update(sql, new Object[]{circle.getCircleId(),circle.getName()});
	}
	
	public int insertIntoCircleByAutoGeneratedPK(String name)
	{
		String sql="INSERT INTO CIRCLE (NAME) VALUES(?)";
		return jdbcTemplate.update(sql, new Object[]{name});
	}
	
	public int getCirclesCount()
	{
		String sql="SELECT COUNT(*) FROM CIRCLE";
		return jdbcTemplate.queryForInt(sql);
	}
}

	
