package com.pvn;



import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.pvn.dao.CircleDaoJDBCImpl;
import com.pvn.model.Circle;

public class JdbcDemo 
{
	@SuppressWarnings("resource")
	public static void main(String[] args) 
	{
		ApplicationContext ctx=new ClassPathXmlApplicationContext("spring.xml");
		CircleDaoJDBCImpl circleDaoJdbcImpl=ctx.getBean("circleDaoJDBCImpl", CircleDaoJDBCImpl.class);
		
		int currentCount=circleDaoJdbcImpl.getCirclesCount();
		currentCount++;
		
		Circle circle=new Circle();
		circle.setCircleId(currentCount);
		circle.setName("Circle"+currentCount++);
		int rowsAffected=circleDaoJdbcImpl.insertIntoCircle(circle);
		System.out.println(rowsAffected+" rows affected");
		
		rowsAffected=circleDaoJdbcImpl.insertIntoCircleByAutoGeneratedPK("Circle"+currentCount++);
		System.out.println(rowsAffected+" rows affected");
		
		for(int i=currentCount;i<currentCount+10;i++)
		{
			circleDaoJdbcImpl.insertIntoCircleByAutoGeneratedPK("Circle"+i);
			System.out.print(i+" ");
		}
		
	}
}
